spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roommate_portal
    username: root
    password: jack

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
